### ISSUE TITLE
Updates not always install

### ISSUE THREAD

**Issue by Frankie24** [mpanighetti/install-or-defer#100]
Hello, I've noticed that after I have deferred the installation, and waited the appropriate time. The updates never install and it doesn't do anything? It doesn't force install.. Do you know why that may be happening?

**Comment by mpanighetti** [comment]
If you manually run Install or Defer.sh with `sudo bash -x` on a Mac experiencing this issue, you'll see a detailed script output that might reveal potential issues while attempting to run macOS updates. Pass over any errors or relevant messages from that run and I'd be happy to take a look.
