### ISSUE TITLE
Updates not installing and are stuck? Need clarification 

### ISSUE THREAD

**Issue by Frankie24** [mpanighetti/install-or-defer#101]
Hello, I have a problem that I've noticed with the install-defer method. I've noticed that it does not run the required security patches such as macOS Monterey 13.2.1 if it's available via the updates panel. If there is a safari update it'll run that instead if clicked on "Install now" at the dialog box. So the security patches are just present there and they never install. This is on the intel macs. Please advise why they do not install?

Thanks,

**Comment by mpanighetti** [comment]
If you manually run Install or Defer.sh with `sudo bash -x` on a Mac experiencing this issue, you'll see a detailed script output that might reveal potential issues while attempting to run macOS updates. Pass over any errors or relevant messages from that run and I'd be happy to take a look.
