### ISSUE TITLE
Catalina

### ISSUE THREAD

**Issue by rossoneris** [mpanighetti/install-or-defer#36]
Hi,

Just tried the package on catalina. But seems to be issues as nothing popup ?
I have been using on on Mojave without issues and it have worked great

Seems some path has changed, but think there is a issue as I have a pending update to 10.15.2 ready

When doing the logging it rapports - and that is just out of the box without I have editited anything

2020-01-10 07:21:52.443848+0100  localhost logger[3367]: Killing any active jamfHelper notifications...
2020-01-10 07:21:52.446838+0100  localhost logger[3367]: Cleaning up stored plist values...
2020-01-10 07:21:52.485014+0100  localhost logger[3367]: Unloading and removing //Library/LaunchDaemons/com.elliotjordan.install_or_defer.plist...
2020-01-10 07:21:52.489440+0100  localhost logger[3367]: //Library/LaunchDaemons/com.elliotjordan.install_or_defer.plist: Could not find specified service
2020-01-10 07:21:52.634995+0100  localhost logger[3378]: //Library/LaunchDaemons/com.elliotjordan.install_or_defer.plist: Path had bad ownership/permissions

**Comment by rossoneris** [comment]
Note: I have used to modified package that should work under Catalina

**Comment by dvbguy** [comment]
I see same issue on this ?

**Comment by mpanighetti** [comment]
Can you give this another try with the latest script build? (v2.3.4) It improves some script cleanup behavior that might be related to what you're seeing in your logs. If that doesn't work, please pass the entirety of your log report in here and I can follow up. Thanks!

**Comment by rossoneris** [comment]
Hi,

still Seems some permission issue on that plist file in Library/launchagent ? 

Caller specified a plist with bad ownership/permissions: path = /Library/LaunchDaemons/com.elliotjordan.install_or_defer.plist, caller = launchctl.29559

**Comment by mpanighetti** [comment]
Is this happening with the [installer package](https://github.com/mpanighetti/install-or-defer/releases/tag/v2.3.4)? I just downloaded that package and ran it on a Catalina Mac and the LaunchDaemon loaded successfully.

If you're manually placing the source files in their respective file paths (LD in /Library/LaunchDaemons, script in /Library/Scripts), the file permissions might be breaking in the process (I just reproduced this behavior in my test environment). In that case, run the following commands to fix the files:

```
chmod +x /Library/Scripts/install_or_defer.sh
chmod 644 /Library/LaunchDaemons/com.elliotjordan.install_or_defer.plist
sudo chown root:wheel /Library/LaunchDaemons/com.elliotjordan.install_or_defer.plist
```

Confirmed on my end that the LaunchDaemon loads successfully after making those adjustments.

**Comment by rossoneris** [comment]
OK - great now it works

Have you thought on the idea to build install and defer for normal poilicies in Jamf ? - would be a great tool, for polcies that can be deferred. Don´t know if that is makeable but think you have most of the "engine" already created for this

**Comment by mpanighetti** [comment]
Definitely something I've been thinking about. If you have thoughts on a good way to implement something like that, my PRs are open. 😁
