### ISSUE TITLE
Convert deferral time to days

### ISSUE THREAD

**Issue by K3ll3r** [mpanighetti/install-or-defer#50]
Hi there,
Do you accept PRs on this project? I tweaked the script in my environment to display the number of days remaining. The default, hours remaining, wasn't super human-readable for longer deferral periods (ours is 1 week, ie 168 hours). I changed it to display days remaining if over 2 days. I'm happy to submit a PR if you think it'd be helpful.

Best,
Dan

**Comment by mpanighetti** [comment]
Yes, pull requests are welcome! This sounds like a beneficial change to bring to the project, happy to test that out once you pass that PR over. Thanks so much!

**Comment by homebysix** [comment]
I've got a [snippet](https://gist.github.com/homebysix/c146214011e9ce64337b8140c5da65ed) I use for just that purpose. I'll be interested to compare with what you come up with.
