### ISSUE TITLE
Running via terminal getting stopped 

### ISSUE THREAD

**Issue by mani2care** [mpanighetti/install-or-defer#52]
Tried via manually running in the terminal and final killing all the apps not happening and getting error and force quite not happen can you find the long 
<img width="882" alt="Screenshot 2021-03-31 at 7 02 35 PM" src="https://user-images.githubusercontent.com/52978899/113157316-68535080-9258-11eb-8dc7-f0facf610a33.png">

**Comment by homebysix** [comment]
This is not something that needs fixing, as the intended method for executing the scrips using a launchdaemon, not manually via Terminal.
