### ISSUE TITLE
not getting pop-up every 4 hour

### ISSUE THREAD

**Issue by pmac789** [mpanighetti/install-or-defer#71]
Hey Mario,
I try your script today, I only got 1 pop which is the beginning when I push out the policy from jamf. am I doing something wrong? it supposed to do a pop-up every 4 hours if user press defer?

**Comment by mpanighetti** [comment]
Yep, the LaunchDaemon reloads regularly in the background and displays the prompt about 4 hours after the last alert, unless you've customized the script or LaunchDaemon payloads and changed the timing. Can you give the latest release a try without any modifications and see if you run into the same issue?

**Comment by pmac789** [comment]
The .pkg that are on the site?
What did you used to wrap it up?

**Comment by mpanighetti** [comment]
Yeah, the .pkg file included in the release is an unmodified default payload you can install directly on your systems. If you're making any changes to the payload (e.g. customizing alert text and branding image), you'll need to assemble the new package. [README includes guidance on using munkipkg to do this](https://github.com/mpanighetti/install-or-defer#installer-creation), but other tools should work fine if preferred.

**Comment by pmac789** [comment]
Thank Mario. I will give this a go again tomorrow as I would like to have
custom logo.
If I need to repackage the installer again I would need to Included the
launchdaimon payload and the post install and pre install script?

**Comment by mpanighetti** [comment]
You'll need all of it to ensure a clean installation (preinstall removes existing resources if you've run it before) and to automate reloading the script each time it prompts the user (post install loads the LaunchDaemon the first time, LaunchDaemon handles the recurring checks).

**Comment by pmac789** [comment]
That exactly what I did the other day using munkipkg and wrapping it up
with .plist for the launchdaimon with post and Pre.

I also trying wrapping it up with composer but I never get the initials
pop-up.

Be great if you would post a quick YouTube tutorial.

**Comment by mpanighetti** [comment]
For what it's worth, [the latest release](https://github.com/mpanighetti/install-or-defer/releases/tag/v5.0) moved custom messaging logos from the script to a configuration profile key, meaning you can make that customization without making any changes to the script or repackaging. Give it a try and see if the alert starts showing up on the unmodified payload.

**Comment by mpanighetti** [comment]
Going to close this out since it seems like you just need to load the LaunchDaemon as part of your deployment.
