### ISSUE TITLE
Support for Monterey?

### ISSUE THREAD

**Issue by K3ll3r** [mpanighetti/install-or-defer#72]
The script currently fails out if a mac is running macOS 12 (line 424). I've been doing testing (modifying the script to pass if the current OS is Monterey) and it seems to work fine. Have there been documented issues, or is it just an outdated conditional that needs to be updated?

**Comment by K3ll3r** [comment]
Ahh, just saw your comment that you're looking into it now. I'll continue testing and wait to hear back.

**Comment by mpanighetti** [comment]
Yep, currently testing it in my environment. But it's helpful to know that you've been using it successfully for enforcing Monterey updates!

**Comment by mpanighetti** [comment]
Added macOS Monterey support in [version 5.0](https://github.com/mpanighetti/install-or-defer/releases/tag/v5.0)!
