### ISSUE TITLE
Issue:- the file tested on 10.15 machine, This mac is 11.2 

### ISSUE THREAD

**Issue by Dharmeshcomputer** [mpanighetti/install-or-defer#75]
unable to update security patch

**Comment by mpanighetti** [comment]
Hi! Could you give a little more information on the issue you're running into and which version of macOS your Mac is running? [I'd recommend giving the latest release a try](https://github.com/mpanighetti/install-or-defer/releases/tag/v5.0), which adds more customization options and improves stability on Apple Silicon Macs. Also, if you're editing the script for your environment, give the unmodified release a try and see if it behaves any better, as that can sometimes reveal issues with script modifications or deployment methods. Keep me posted!

**Comment by Dharmeshcomputer** [comment]
The New release is giving an error. We have a locked software update option in system preferences, it's, again and again, poping up to go there. Screenshot attached. one more thing " sudo softwareupdate -a -i --restart" is working fine. but need to create policy in JamF. 

<img width="644" alt="Screenshot 2022-02-16 at 11 27 28 PM" src="https://user-images.githubusercontent.com/99245020/154327076-7069af61-5417-43fe-b135-34555173039f.png">
<img width="555" alt="Screenshot 2022-02-16 at 11 29 10 PM" src="https://user-images.githubusercontent.com/99245020/154327052-d6ccd9f0-9cdc-4dd1-ac3a-0471a2db7efc.png">

**Comment by mpanighetti** [comment]
Oh interesting. This workflow didn't take into account that folks might be blocking the Software Update preference. You could change the wording of the alert text to remove references to the manual update option if you don't want to direct folks there, at least on Intel Macs; Apple Silicon Macs will need the user to manually apply the update via the System Preferences UI; [see the README for the rationale behind this behavior](https://github.com/mpanighetti/install-or-defer#limitations).

**Comment by mpanighetti** [comment]
[Added a note to Limitations on the README](https://github.com/mpanighetti/install-or-defer#limitations) to clarify that running this script on Apple Silicon Macs requires the user to have a secure token, volume ownership, and the ability to open the Software Update preference pane. Thanks for flagging this behavior!
