### ISSUE TITLE
FR: Add a AC power requirement?

### ISSUE THREAD

**Issue by master-vodawagner** [mpanighetti/install-or-defer#83]
As we all know Apple are really pushing MDM commands for software updates, it would be good to add in the below feature?

1. Optional setting in PLIST to enable power source checking with a timer?
2. If enabled, prompt the user to plug-in power with a countdown timer?

**Comment by mpanighetti** [comment]
I like the idea of encouraging power adapter connections for a smoother update experience, but a simpler solution might be to just put a note to connect a power adapter in all the alert messages. This wouldn't require custom config profile keys or explicit checks of the current power adapter state.

If the goal is to _require_ a power adapter, having a countdown timer doesn't constitute a hard requirement. Considering the goal of this framework is to apply updates by a set deadline, having the power adapter be a hard requirement implies the update would be deferred further if the user doesn't plug one in, which provides a simple avenue to put off an update indefinitely. I don't think that's the best approach.

I'm going to put the power adapter note in the alert descriptions to encourage best practices, but let me know if you have more thoughts on what the behavior would be with explicit power adapter checks.
