### ISSUE TITLE
convert_seconds command not found

### ISSUE THREAD

**Issue by master-vodawagner** [mpanighetti/install-or-defer#87]
I think you might need to move the timing section below the function?  Currently it errors out I'm guessing at the point of calculating seconds the script isn't aware of the convert_seconds function?

X:~ root# /Library/Scripts/install-or-defer.sh
Calculating script timing...
/Library/Scripts/install-or-defer.sh: line 248: convert_seconds: command not found
Maximum deferral time: 
/Library/Scripts/install-or-defer.sh: line 255: convert_seconds: command not found
Deferral period: 
/Library/Scripts/install-or-defer.sh: line 262: convert_seconds: command not found
Prompt timeout: 
/Library/Scripts/install-or-defer.sh: line 269: convert_seconds: command not found
Update delay: 
/Library/Scripts/install-or-defer.sh: line 276: convert_seconds: command not found
Hard restart delay:

**Comment by mpanighetti** [comment]
Good catch, thanks! Should be fixed in #88.
