### ISSUE TITLE
Update Install or Defer profile manifest in ProfileManifestsMirror

### ISSUE THREAD

**Issue by briancuerdon** [mpanighetti/install-or-defer#89]
The Install of Defer profile manifest in [ProfileManifestsMirror](https://github.com/Jamf-Custom-Profile-Schemas/ProfileManifestsMirror/blob/main/manifests/ManagedPreferencesApplications/com.github.mpanighetti.install-or-defer.json) needs to be updated to add support for the new configuration profile keys.

**Comment by mpanighetti** [comment]
Thanks for the reminder! I've submitted a PR with all the new configuration profile keys to ProfileManifests: https://github.com/ProfileCreator/ProfileManifests/pull/551

Once that's merged, ProfileManifestsMirror will update automatically.
