### ISSUE TITLE
FR: Add a dropdown box with a selection of defer times?

### ISSUE THREAD

**Issue by master-vodawagner** [mpanighetti/install-or-defer#90]
Wondered if we can give the EUD user some flexibility in the defer time per prompt?

A Dropdown box with a selection of deferment times which could be customised using the configuration profiles in Jamf.

**Comment by mpanighetti** [comment]
I like the idea of multiple deferral period options, but jamfHelper does not support a dropdown or multiple selections in its interface (beyond its two buttons), so this would require a complete rewrite to use another alert prompt system, like AppleScript or a third-party application. It's not likely I'll be pursuing such a drastic shift in this project.
