### ISSUE TITLE
Ignoring macOS Upgrades

### ISSUE THREAD

**Issue by mazeorelt** [mpanighetti/install-or-defer#96]
Hey,

i might wonder, if it is possible to ignore here an upgrade? 
We got a bunch of macos 11 and before getting into macos 13, I just want to update to ex. 11.8 or so.

Thanks!

**Comment by mpanighetti** [comment]
The ability to ignore specific updates was removed from the `softwareupdate` binary starting with macOS Big Sur. Is macOS 13 being advertised in the script output as an available update? I know that's happening with Monterey but wasn't sure if that behavior extended back to Big Sur.

**Comment by mpanighetti** [comment]
Based on this feedback, I'm going to add macOS Big Sur to scope for ignoring "macOS Ventura" releases listed in `softwareupdate --list` output.
